In [1]:
import numpy as np

1D with Numpy

In [4]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

print('Rank of t: ', t.ndim) # dimensionality
print('Shape of t: ', t.shape) # 1 x 7

[0. 1. 2. 3. 4. 5. 6.]
Rank of t:  1
Shape of t:  (7,)


Numpy Basics

In [7]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # access w/ index
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])
print('t[:2] t[3:] = ', t[:2], t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


2D with Numpy

In [10]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12]])
print(t)

print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape) # 4 x 3 : 4 rows, 3 columns

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank of t:  2
Shape of t:  (4, 3)


1D with PyTorch

In [11]:
import torch

ModuleNotFoundError: No module named 'torch'